release-date = "2026-02-16"

[[entries]]
id = "afe1b9c3-a4d9-4f33-9587-ae430f672646"
type = "deprecation"
description = "Rename `GithubApp.get_installation_token_supplier()` to `.installation_token_supplier()` for consistency"
author = "@NiklasRosenstein"

[[entries]]
id = "1e882ab7-ae70-44ac-a58f-de8e7829f696"
type = "fix"
description = "Hide `GithubApp.private_key` from `repr()`"
author = "@NiklasRosenstein"

[[entries]]
id = "dd92343b-4e35-4d03-9990-82189fba8aad"
type = "feature"
description = "Add API for initiating OAuth2 Web application and Device flows"
author = "@NiklasRosenstein"

[[entries]]
id = "d62bf2e4-15e4-4989-933f-f8ac4bb68eed"
type = "fix"
description = "Ensure `iss` claim is a string"
author = "@tun0"
pr = "https://github.com/NiklasRosenstein/python-github-bot-api/issues/26"
