name: github-bot-api
version: 0.3.3
author: Niklas Rosenstein <nrosenstein@palantir.com>
description: API for creating GitHub bots and webhooks in Python.
url: https://github.com/NiklasRosenstein/python-github-bot-api
license: MIT
requirements:
- python ^3.8
- PyJWT ^1.7.1
- cryptography ^3.1.1
- requests ^2.25.0
typed: true
test-requirements:
- PyGithub
- types-flask
- types-jwt
- types-requests
dev-requirements:
- flask
- PyGithub
test-drivers:
- type: mypy
