name: github-bot-api
version: 0.5.1
author: Niklas Rosenstein <nrosenstein@palantir.com>
license: MIT
url: https://niklasrosenstein.github.io/python-github-bot-api/
description: API for creating GitHub bots and webhooks in Python.
typed: true
requirements:
- python ^3.8
- PyJWT ^2.0.0
- cryptography ^3.1.1
- requests ^2.25.0
- Deprecated ^1.2.12
- urllib3 ^1.26.6
- nr.functional ^0.2.0
test-requirements:
- PyGithub
- types-deprecated
- types-flask
- types-requests
dev-requirements:
- flask
- PyGithub
test-drivers:
- args:
  - --show-error-codes
  - --warn-unused-ignores
  type: mypy
- type: pytest
