# This file was auto-generated by Shut. DO NOT EDIT
# For more information about Shut, check out https://pypi.org/project/shut/

from __future__ import print_function
import io
import os
import setuptools
import sys

readme_file = 'README.md'
source_readme_file = '../README.md'
if not os.path.isfile(readme_file) and os.path.isfile(source_readme_file):
  import shutil; shutil.copyfile(source_readme_file, readme_file)
  import atexit; atexit.register(lambda: os.remove(readme_file))
if os.path.isfile(readme_file):
  with io.open(readme_file, encoding='utf8') as fp:
    long_description = fp.read()
else:
  print("warning: file \"{}\" does not exist.".format(readme_file), file=sys.stderr)
  long_description = None

requirements = [
  'PyJWT >=1.7.1,<2.0.0',
  'cryptography >=3.1.1,<4.0.0',
  'requests >=2.25.0,<3.0.0',
]

setuptools.setup(
  name = 'github-bot-api',
  version = '0.1.0',
  author = 'Niklas Rosenstein',
  author_email = 'nrosenstein@palantir.com',
  description = 'Package description here.',
  long_description = long_description,
  long_description_content_type = 'text/markdown',
  url = None,
  license = None,
  packages = setuptools.find_packages('src', ['test', 'test.*', 'tests', 'tests.*', 'docs', 'docs.*']),
  package_dir = {'': 'src'},
  include_package_data = True,
  install_requires = requirements,
  extras_require = {},
  tests_require = [],
  python_requires = '>=3.5.0,<4.0.0',
  data_files = [],
  entry_points = {},
  cmdclass = {},
  keywords = [],
  classifiers = [],
  zip_safe = True,
)
