name: Pylint

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.x" ]
    steps:
    - uses: actions/checkout@v2
    - uses: python-slap/slap.cli@gha/install/v1
    - uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - run: slap install -vv --no-venv-check
    - run: slap test

  documentation:

    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/develop'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: python -m pip install pydoc-markdown==4.2.0 mkdocs -q
    - name: Generate docs
      run: pydoc-markdown --build --site-dir "$PWD/_html"
    - name: Publish docs
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: _html
        ssh-key: ${{ secrets.DEPLOY_KEY }}
