name: Pylint

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.x']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install shut==0.21.0 -q
    - name: Test
      run: shut pkg test --isolate
    - name: Verify package metadata
      run: shut pkg update --verify

  documentation:

    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/develop'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: python -m pip install pydoc-markdown==4.2.0 mkdocs -q
    - name: Generate docs
      run: pydoc-markdown --build --site-dir "$PWD/_html"
    - name: Publish docs
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: _html
        ssh-key: ${{ secrets.DEPLOY_KEY }}
