name: Python

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13" ]
    steps:
    - uses: actions/checkout@v3
    - uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.14"
        python-version: "${{ matrix.python-version }}"
    - uses: actions/setup-python@v5
      with:
        python-version: "${{ matrix.python-version }}"
    - run: uv sync --all-extras --dev
    - run: uv run ruff check .
    - run: uv run ruff format --check .
    - run: uv run mypy .
    - run: uv run pytest .

  documentation:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@v3
    - uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.14"
    - run: uvx --from slap-cli slap changelog format --markdown --all > docs/content/changelog.md
    - run: cd docs && uv run mkdocs build --site-dir _site
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs/_site
        ssh-key: ${{ secrets.DEPLOY_KEY }}
